//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodBucket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Recipies = new HashSet<Recipy>();
        }
    
        public int id_country { get; set; }
        public string name { get; set; }
        public string image_con { get; set; }
    
        public virtual ICollection<Recipy> Recipies { get; set; }
    }
}
