//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodBucket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipies
    {
        public Recipies()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int id_recipe { get; set; }
        public int id_country { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string ingredients { get; set; }
        public string preparation { get; set; }
        public string extra_description { get; set; }
        public string image_rec { get; set; }
    
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Countries Countries { get; set; }
    }
}
